language: android
android:
  components:
    - build-tools-25.0.2
    - $ANDROID_TARGET
    - sys-img-armeabi-v7a-$ANDROID_TARGET
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
before_install:
  - chmod +x gradlew
env:
  matrix:
    - ANDROID_TARGET=android-25  ANDROID_ABI=armeabi-v7a